Audio.class: Audio.java
	javac -g Audio.java

Game.class: Game.java
	javac -g Game.java

Hook.class: Hook.java
	javac -g Hook.java

Player.class: Player.java
	javac -g Player.java

Player2.class: Player2.class
	javac -g Player2.java

Scene.class: Scene.java
	javac -g scene.java

Sprite.class: Sprite.java
	javac -g Sprite.java

run: Game.class
	java Game

clean:
	rm *.class
